#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 || "$2" != "--bundle" ]]; then
  echo "Usage: $0 /absolute/path/to/approved_map.pcd --bundle /path/to/execution_bundle.json" >&2
  exit 2
fi
map_pcd="$1"
bundle="$3"
[[ "$map_pcd" = /* ]] || { echo "Map path must be absolute." >&2; exit 2; }
[[ -s "$map_pcd" ]] || { echo "Approved map is missing or empty: $map_pcd" >&2; exit 2; }
[[ -s "$bundle" ]] || { echo "Execution bundle is missing or empty: $bundle" >&2; exit 2; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
runtime_root="$(cd "$script_dir/.." && pwd)"
dls_ws="${DLS_WS:-/home/nv/dls_ws}"
config="$runtime_root/config/super_indoor_stage2.yaml"
launch="$runtime_root/launch/super_indoor_stage2.launch"
collision_builder="$runtime_root/scripts/build_super_collision_pcd.py"
collision_voxel="${PRE_MAP_VLN_SUPER_STATIC_VOXEL:-0.15}"
collision_cache="${PRE_MAP_VLN_SUPER_CACHE:-$HOME/.cache/pre_map_vln/super_collision}"
map_name="$(basename "${map_pcd%.pcd}")"
bundle_hash="$(sha256sum "$bundle" | awk '{print $1}')"
collision_pcd="$collision_cache/${map_name}_voxel_${collision_voxel}_launch_${bundle_hash:0:12}.pcd"
collision_metadata="${collision_pcd}.json"

[[ -r "$config" && -r "$launch" && -r "$collision_builder" ]] || { echo "Missing Stage-2 SUPER files." >&2; exit 2; }
[[ -r "$dls_ws/devel/setup.bash" ]] || { echo "Missing senior dls_ws build." >&2; exit 2; }

unset _CATKIN_SETUP_DIR || true
set +u
source /opt/ros/noetic/setup.bash
source "$dls_ws/devel/setup.bash"
set -u

rostopic info /ekf_quat/ekf_odom >/dev/null 2>&1 || {
  echo "Missing /ekf_quat/ekf_odom; establish and verify global localization first." >&2
  exit 1
}
rostopic info /cloud_registered >/dev/null 2>&1 || {
  echo "Missing /cloud_registered; SUPER cannot build its live collision map." >&2
  exit 1
}
if rosnode list 2>/dev/null | grep -Fxq /fsm_node; then
  echo "SUPER /fsm_node is already running; stop its existing terminal first." >&2
  exit 1
fi
if rosnode list 2>/dev/null | grep -Fxq /px4ctrl; then
  echo "PX4Ctrl is already running. Planner startup is allowed, but this script sends no goal." >&2
fi

echo "Preparing cached occupied prior for SUPER (original map remains unchanged)."
python3 "$collision_builder" "$map_pcd" "$collision_pcd" \
  --voxel "$collision_voxel" --bundle "$bundle"
[[ -s "$collision_metadata" ]] || { echo "Missing collision metadata: $collision_metadata" >&2; exit 1; }

echo "Starting senior SUPER with the PRE_MAP_VLN low-speed indoor profile."
echo "Localization/original map: $map_pcd"
echo "Sparse SUPER occupied prior: $collision_pcd"
echo "Launch clearance bundle SHA256: $bundle_hash"
echo "No mission goal, arm, takeoff, landing, or PositionCommand is generated by this script."
exec roslaunch "$launch" "config_path:=$config" "map_pcd:=$collision_pcd" \
  "bundle_sha256:=$bundle_hash" "collision_metadata:=$collision_metadata"
