#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 /absolute/path/to/approved_map.pcd" >&2
  exit 2
fi
map_pcd="$1"
[[ "$map_pcd" = /* ]] || { echo "Map path must be absolute." >&2; exit 2; }
[[ -s "$map_pcd" ]] || { echo "Approved map is missing or empty: $map_pcd" >&2; exit 2; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
runtime_root="$(cd "$script_dir/.." && pwd)"
dls_ws="${DLS_WS:-/home/nv/dls_ws}"
config="$runtime_root/config/super_indoor_stage2.yaml"
launch="$runtime_root/launch/super_indoor_stage2.launch"

[[ -r "$config" && -r "$launch" ]] || { echo "Missing Stage-2 SUPER files." >&2; exit 2; }
[[ -r "$dls_ws/devel/setup.bash" ]] || { echo "Missing senior dls_ws build." >&2; exit 2; }

unset _CATKIN_SETUP_DIR || true
set +u
source /opt/ros/noetic/setup.bash
source "$dls_ws/devel/setup.bash"
set -u

rostopic info /ekf_quat/ekf_odom >/dev/null 2>&1 || {
  echo "Missing /ekf_quat/ekf_odom; establish and verify global localization first." >&2
  exit 1
}
rostopic info /cloud_registered >/dev/null 2>&1 || {
  echo "Missing /cloud_registered; SUPER cannot build its live collision map." >&2
  exit 1
}
if rosnode list 2>/dev/null | grep -Fxq /px4ctrl; then
  echo "PX4Ctrl is already running. Planner startup is allowed, but this script sends no goal." >&2
fi

echo "Starting senior SUPER with the PRE_MAP_VLN low-speed indoor profile."
echo "Static occupied prior: $map_pcd"
echo "No mission goal, arm, takeoff, landing, or PositionCommand is generated by this script."
exec roslaunch "$launch" "config_path:=$config" "map_pcd:=$map_pcd"
